RA-13 initial
morganharry/RecipeApp pull request #12
Opened 2023-11-22 02:17 UTC by morganharry

2023-11-23 16:40 UTC, danelyan requested changes

2023-11-23 16:40 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/RecyclerViewItemDecoration.kt
> +    private var mDivider: Drawable = ContextCompat.getDrawable(context, resId)!!
Да, в целом валидное решение с декоратором.
Но я бы не использовал целый Drawable для такого простого случая, тут ты можешь нарисовать линию прямо на канвасе. 

Давай тут заменим на:
```Kotlin
private val paint = Paint().apply {
    color = lineColor
}
```
Этот paint будем использовать для рисования линии

2023-11-23 16:40 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/RecyclerViewItemDecoration.kt
> +    resId: Int
Сюда давай не будем передавать контекст, ограничимся
```Kotlin
class RecyclerViewItemDecoration(
    lineColor: Int
) : RecyclerView.ItemDecoration() {
...
```

2023-11-23 16:40 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/RecyclerViewItemDecoration.kt
> +        val dividerLeft: Int = 32
Так делать не вполне корректно, когда рисуешь на Canvas, нужно использовать px, то есть размеры для данного экрана.  Ведь все margin и padding ты задаешь через dp, которые конвертируются для твоего экрана. Если оставить так - отступы будут выглядеть разными для разных плотностей пикселей.

Обычно на проектах используют пару таких экстеншенов:

```Kotlin
val Int.px: Int get() = (this * getSystem().displayMetrics.density).toInt()
val Int.dp: Int get() = (this / getSystem().displayMetrics.density).toInt()
```
Для конвертации одного в другое. Получится так:
```Kotlin
val dividerLeft = 8.px
val dividerRight = parent.width - 8.px
```

8 - потому что 32 это 8 dp для xxxhdpi https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp

2023-11-23 16:40 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/RecyclerViewItemDecoration.kt
> +                mDivider.draw(c)
И тут заменим лишь три строки:
```Kotlin
val dividerBottom = dividerTop + 1.px
val rect = Rect(dividerLeft, dividerTop, dividerRight, dividerBottom)
c.drawRect(rect, paint)
```

2023-11-23 16:40 UTC, danelyan commented on app/src/main/res/layout/fragment_recipe.xml
> +        android:background="@color/main_background_color"
зачем этот background? так добавляются лишние перерисовки экрана

2023-11-23 18:06 UTC, morganharry commented on app/src/main/java/com/example/recipeapp/RecyclerViewItemDecoration.kt
> +    private var mDivider: Drawable = ContextCompat.getDrawable(context, resId)!!
Странно, но почему-то цвет в фигуру не передает. не могу понять почему.

2023-11-24 07:10 UTC, danelyan requested changes

2023-11-24 07:10 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        getContext()?.let { RecyclerViewItemDecoration(R.color.line_list_color) }
R.color.line_list_color - это **идентификатор ресурса** - тоже число, а Canvas оперирует **численными представлениями цвета**. Это по сути ARGB формата 0xFFFFFFFF, только в 10-ом представлении.
Короче:
```Kotlin
 context?.getColor(R.color.line_list_color)
```

2023-11-24 15:23 UTC, danelyan approved these changes

2023-11-24 16:20 UTC, merged