RA-16_favorite_button
morganharry/RecipeApp pull request #15
Opened 2023-12-02 05:45 UTC by morganharry

2023-12-02 17:27 UTC, ievetrov requested changes

2023-12-02 17:27 UTC, ievetrov commented on app/src/main/res/layout/fragment_recipe.xml
> +            <ImageButton
Добавим еще для всех изображений и кнопок с изображениями contentDescription. Для скринридеров, чтобы люди с плохим зрением могли пользоваться приложением.

2023-12-02 18:39 UTC, morganharry commented on app/src/main/res/layout/fragment_recipe.xml
> +            <ImageButton
> Добавим еще для всех изображений и кнопок с изображениями contentDescription. Для скринридеров, чтобы люди с плохим зрением могли пользоваться приложением.

Добавил, но я так понимаю в идеале их надо будет еще переназначать, в зависимости подтягиваемого объекта категории/рецепта, в дальнейшем когда оптимизируем подтягивание объектов в ReycleView. Верно?

2023-12-03 07:47 UTC, ievetrov approved these changes

2023-12-03 07:47 UTC, ievetrov commented on app/src/main/res/layout/fragment_recipe.xml
> +            <ImageButton
Если контент не поставляется от условного заказчика, то с нашей стороны достаточно описать "это изображение рецепта". Описывать картинку это уже к копирайтерам) Потому что как правило всегда есть заголовки экранов, секций, элементов.. и по ним можно осуществлять навигацию.

2023-12-03 08:40 UTC, merged