RA-20_viewmodel_for_recipes
morganharry/RecipeApp pull request #19
Opened 2023-12-09 06:13 UTC by morganharry

2023-12-09 19:16 UTC, danelyan requested changes

2023-12-09 19:16 UTC, danelyan commented on app/build.gradle.kts
> +    implementation("androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version")
Эти зависимости объявлять не обязательно, так как они транзитивно добавляются другими библиотеками.
В частности - `fragment-ktx` транзитивно добавляет `lifecycle-viewmodel`.
В этом можно убедиться запустив `./gradlew app:dependencies`:
![photo_2023-12-09 22 11 55](https://github.com/morganharry/RecipeApp/assets/7125622/6bb67276-259f-4d79-a8ca-7596dc15480f)

2023-12-09 19:16 UTC, danelyan commented on app/build.gradle.kts
> +        dataBinding = true
Для чего был добавлен dataBinding?

> dataBinding — это библиотека поддержки, которая позволяет вам привязывать компоненты пользовательского интерфейса в ваших макетах к источникам данных в вашем приложении, используя декларативный формат, а не кодом.

2023-12-10 06:25 UTC, morganharry commented on app/build.gradle.kts
> +    implementation("androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version")
А как ты запускаешь ./gradlew app:dependencies?
![image](https://github.com/morganharry/RecipeApp/assets/101452247/18f84344-9d07-48d0-9b17-2ddc5ed82511)

2023-12-11 18:40 UTC, ievetrov approved these changes

2023-12-11 19:01 UTC, merged