RA-03_initial
morganharry/RecipeApp pull request #2
Opened 2023-10-22 13:35 UTC by morganharry

2023-10-23 18:25 UTC, morganharry commented
1. Какой-то затык с Темой. Вроде бы назначил ее на кнопки, но атрибуты Темы не влияют на стиль кнопок.
Кроме того еще и манифест весь в красный покрасило (не могу понять , связано ил нет).
2. Проворонил и назвал приложение RecipeApp в единственном числе. Поэтому вопрос- как правильно поменять название везде, не сломав при этом ничего?

2023-10-23 19:39 UTC, ievetrov commented
Окрашенный манифест не должен играть роль. Это решается пересборкой проекта или его пересинхронизацией (иконка слоника)

2023-10-23 19:54 UTC, ievetrov commented
отображаемое название меняется в ресурсах в айтеме app_name. 
как в файловой системе поменять, чтобы ничего не сломать - без гарантий можно нагуглить гайды. с кучей ренеймов разных конфигов https://www.delasign.com/blog/android-studio-rename-project/

2023-10-23 19:54 UTC, ievetrov requested changes

2023-10-23 19:54 UTC, ievetrov commented on app/src/main/res/values/themes.xml
> +    <style name="StyleNavButton" parent="Widget.Material3.Button">
давай перенесем тоже в стили, темы тут не причем и мы их вообще не кастомим.

2023-10-23 19:54 UTC, ievetrov commented on app/src/main/res/values/themes.xml
> +        <item name="android:windowLightStatusBar">true</item>
надо оставить в каком-то одном месте, чтобы не дублировалось

2023-10-23 19:54 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +            android:theme="@style/StyleNavButton" />
это не тема, нужен именно атрибут стиль (и не забудь перенести стиль кнопок в стили)

2023-10-24 14:47 UTC, ievetrov requested changes

2023-10-24 14:47 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_margin="@dimen/Main_Layout_Margin"
- можно применить марджин только для горизонтала (чтобы не делить и не добавлять отдельный такой же у кнопки)
- в качестве нейминга еще можно обычно так делать - объявить основной отступ, половину отступа (half) и т д.

пример
`android:layout_marginHorizontal="@dimen/space_standard"`

2023-10-24 14:47 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_margin="@dimen/Main_Layout_Margin"
и нейминг для ресурсов лучше однообразный (как для строк) snake_case

2023-10-24 14:47 UTC, ievetrov commented on app/src/main/res/values/dimens.xml
> +    <dimen name="Main_Button_Margin">8dp</dimen>
и одного стандартного 16 и половины от стандартного 8 отступа будет достаточно (не обязательно выносить дублированные отступы)

2023-10-24 14:47 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
>              app:icon="@drawable/ic_heart"
а ты точно корректно svg экспортил из фигмы? выглядит как-то сплющенно по горизонтали

2023-10-24 14:56 UTC, ievetrov requested changes

2023-10-24 14:56 UTC, ievetrov commented on app/src/main/res/values/colors.xml
> +    <color name="MainBackgroundColor">#FFFFFFFF</color>
основной цвет макета, кстати, не чисто белый. надо повнимательнее посмотреть

2023-10-24 14:56 UTC, ievetrov commented on app/src/main/res/values/colors.xml
> +    <color name="TextNavButtonColor">#FFFFFFFF</color>
в принципе можно использовать уже определенный белый, чтобы не дублировать.

2023-10-24 18:14 UTC, morganharry commented on app/src/main/res/values/colors.xml
> +    <color name="TextNavButtonColor">#FFFFFFFF</color>
> в принципе можно использовать уже определенный белый, чтобы не дублировать.

А вдруг менеджер попросит цвет текста кнопок поменять на синий? мне придётся добавлять новый ресурс или проверять где еще этот белый участвует, прежде чем новый HEX вставлять. А тут в два клика поменять.

2023-10-24 18:21 UTC, morganharry commented on app/src/main/res/layout/activity_main.xml
>              app:icon="@drawable/ic_heart"
Да так и есть. Но плющит AS. Пока пытаюсь понять почему.

2023-10-25 12:46 UTC, ievetrov commented on app/src/main/res/values/colors.xml
> +    <color name="TextNavButtonColor">#FFFFFFFF</color>
ага, окей норм!

2023-10-25 12:51 UTC, ievetrov approved these changes
все отлично!
про иконки написал в ЛС

2023-10-26 03:17 UTC, merged