RA-23 receive recipe in vm
morganharry/RecipeApp pull request #28
Opened 2023-12-20 02:36 UTC by morganharry

2023-12-22 22:18 UTC, ievetrov requested changes

2023-12-22 22:18 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
>          })
Нет необходимости проверять на null явно в строке `if (ingredientsAdapter != null) {`. Достаточно вызывать метод через оператор безопасного вызова

2023-12-22 22:18 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
>          })
также внутри метода изменения прогресса дублируется строка инициализации адаптера
`recyclerIngredientsView.adapter = ingredientsAdapter`

2023-12-22 22:18 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipeslist/RecipesListFragment.kt
> +        val recipesAdapter = listRecipes?.let { RecipesListAdapter(it, this) }
`listRecipes` ненулябельная переменная. в нее сохранится либо список рецептов, либо пустой список. следовательно оператор безопасного вызова и let тут лишние

2023-12-22 22:18 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipeslist/RecipesListFragment.kt
> +        if (recipesAdapter != null) {
как и эта проверка

2023-12-22 22:18 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +        _recipeLiveData.value = RecipeState(null, null, false)
Можно закомментировать или удалить. Теперь первичная загрузка происходит через метод загрузки рецепта

2023-12-23 04:58 UTC, morganharry commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
>          })
> также внутри метода изменения прогресса дублируется строка инициализации адаптера `recyclerIngredientsView.adapter = ingredientsAdapter`

Но ведь мы меняем прогресс и меняем значение в количестве ингредиентов. Как по другому?

2023-12-23 10:39 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
>          })
> > также внутри метода изменения прогресса дублируется строка инициализации адаптера `recyclerIngredientsView.adapter = ingredientsAdapter`
> 
> Но ведь мы меняем прогресс и меняем значение в количестве ингредиентов. Как по другому?

Есть один полезный метод, который стоит взять на вооружение. Его запуск уведомляет элементы вью холдера о том, что набор данных изменился и их надо перерисовать.
https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.Adapter#notifyDataSetChanged()

2023-12-24 00:15 UTC, ievetrov requested changes

2023-12-24 00:15 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +            initUI(viewModel.recipeLiveData)
Это не очень корректный подход к передаче стейта в наблюдателе. Обновленный стейт у тебя приходит в параметры лямбды в переменную it. Можно явно прописать ее название, чтобы не возникало таких ситуаций, когда она незаметна

2023-12-24 11:57 UTC, ievetrov approved these changes

2023-12-24 11:57 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +                recyclerIngredientsView.adapter?.notifyDataSetChanged()
В следующем ПР давай уведомление адаптера перенесем в сам адаптер, в метод updateIngredients. Лишнюю строку обращения если можно убрать из фрагмента – лучше это делать.

2023-12-25 04:00 UTC, merged