RA-04_first_fragment
morganharry/RecipeApp pull request #3
Opened 2023-10-26 03:30 UTC by morganharry

2023-10-28 06:35 UTC, ievetrov requested changes

2023-10-28 06:35 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +    android:background="#FDF4FF"
для бэкграунда уже есть вынесенный в ресы цвет (ниже его закомментил?)

2023-10-28 06:35 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +                add<CategoriesListFragment>(R.id.mainContainer)
для метода add отсутствует имплементация импорт библиотеки.

В целом всегда когда видишь подсвечиваемую ошибку - сначала наводишь курсором и изучаешь что оно хочет, затем смотришь предлагаемые варианты. вот в данном случае проблема решается так

<img width="455" alt="image" src="https://github.com/morganharry/RecipeApp/assets/34489023/39f003bc-ed22-4b9c-b83a-5b01bf66bc97">

2023-10-28 06:35 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginHorizontal="@dimen/space_standard"
по отступам. этот контейнер - будет фактически целиком представлять экран. поэтому отступов сверху и по бокам быть не должно

2023-10-28 06:35 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +                add<CategoriesListFragment>(R.id.mainContainer)
Предлагаю использовать replace() вместо add(), так как в этом случае новые фрагменты не будут накладываться друг на друга, а заменяться новым. Чтобы их стек был пуст. 

Иначе может возникнуть ситуация, когда новый фрагмент еще не прогрузится и у него будет условно прозрачный фон. И пользователь может увидеть что-то на другом фрагменте, что ему не нужно видеть

2023-10-28 06:35 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +                add<CategoriesListFragment>(R.id.mainContainer)
Про replace() в доке почти сразу говорится https://developer.android.com/guide/fragments/fragmentmanager#perform

2023-10-28 09:55 UTC, ievetrov approved these changes
отлично!

2023-10-28 10:46 UTC, morganharry commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +                add<CategoriesListFragment>(R.id.mainContainer)
Вопросы:
задача 2. 
- Можем ли (надо ли) во Фрагменте реализовать backing property, как мы сделали в MainActivity?
- Я правильно понимаю, что для Фрагмента `onCreateView()` возвращает View?, тем самым передает ресурс разметки Фрагмента, а метод Активити `onCreate() `не возвращает ничего, но передает ресурс разметки Активити через вызов `setContentView()`? Меня смущает разное поведение методов. Или я зря их поведение друг с другом ассоциирую?
задача 4.
- Ты пишешь "Чтобы растянуть контейнер на весь экран, нужно атрибуту layout_height задать значение 0dp. ", а разве `match_parent` не сделает тоже самое?
задача 5.
- Вот тут самое большое недопонимание. Я не вижу связки, где в созданный контейнер для фрагментов `mainContainer` попадает созданная и раздутая разметка `fragment_list_categories`?

2023-10-28 10:47 UTC, morganharry commented
Вопросы:
задача 2. 
- Можем ли (надо ли) во Фрагменте реализовать backing property, как мы сделали в MainActivity?
- Я правильно понимаю, что для Фрагмента `onCreateView()` возвращает View?, тем самым передает ресурс разметки Фрагмента, а метод Активити `onCreate() `не возвращает ничего, но передает ресурс разметки Активити через вызов `setContentView()`? Меня смущает разное поведение методов. Или я зря их поведение друг с другом ассоциирую?

задача 4.
- Ты пишешь "Чтобы растянуть контейнер на весь экран, нужно атрибуту layout_height задать значение 0dp. ", а разве `match_parent` не сделает тоже самое?

задача 5.
- Вот тут самое большое недопонимание. Я не вижу связки, где в созданный контейнер для фрагментов `mainContainer` попадает созданная и раздутая разметка `fragment_list_categories`?

2023-10-29 11:33 UTC, merged

2023-10-30 20:47 UTC, ievetrov commented
> Вопросы: задача 2.
> 
> * Можем ли (надо ли) во Фрагменте реализовать backing property, как мы сделали в MainActivity?
> * Я правильно понимаю, что для Фрагмента `onCreateView()` возвращает View?, тем самым передает ресурс разметки Фрагмента, а метод Активити `onCreate() `не возвращает ничего, но передает ресурс разметки Активити через вызов `setContentView()`? Меня смущает разное поведение методов. Или я зря их поведение друг с другом ассоциирую?
> 
> задача 4.
> 
> * Ты пишешь "Чтобы растянуть контейнер на весь экран, нужно атрибуту layout_height задать значение 0dp. ", а разве `match_parent` не сделает тоже самое?
> 
> задача 5.
> 
> * Вот тут самое большое недопонимание. Я не вижу связки, где в созданный контейнер для фрагментов `mainContainer` попадает созданная и раздутая разметка `fragment_list_categories`? (возможно через replace(R.id.mainContainer)?)
> * В каком случае мы указываем в разметке контейнера для фрагментов атрибут android:name?

1. по сути это 2 подхода. через lateinit или backing property. мне нравится второй, тк ошибка в данном случае будет более точная. и в целом использование lateinit плохой тон в андройд разработке
2. да, не стоит ассоциировать поведение этих двух методов. потому, что фрагмент - это по сути более сложное вью. а метод onCreateView() вызывается из FragmentManager (как бы прося тебя создать вью). активити же это объект операционной системы
3. m_parent используется для более простых контейнеров (не констрейнт). внутри констрейнт лейаут позиционирование осуществляется через привязку (констрейнты). при m_parent контейнер проигнорирует ограничения рядом находящегося контейнера (с кнопками) и задаст принудительно размер родителя - то есть всего экрана. 0dp позволяет задать динамический размер
4. в MainActivity делаешь реплейс, указывая fragment_list_categories в качестве аргумента типа (и mainContainer, где фрагмент будет отображаться). FragmentManager внутри создает экземпляр categories fragment и вызывает onCreateView(), который приводит к инфлейту созданной разметки. 
5. в твоем случае name будет игнорироваться, потому что CategoriesListFragment наследуется от Fragment(). name нужно использовать если в разметке используется тег <fragment> - для определения класса фрагмента, который должен быть инстанциирован и отображен в этом контейнере.