RA-26_refactor_rv
morganharry/RecipeApp pull request #31
Opened 2023-12-26 02:35 UTC by morganharry

2023-12-26 13:48 UTC, ievetrov requested changes

2023-12-26 13:48 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +    private var ingredientsAdapter = recipeIngredients?.let { IngredientsAdapter(listOf()) }
Вот тут создается экземпляр адаптера через `IngredientsAdapter(listOf())` с пустым списком. Это то, что требуется сделать при инициализации фрагмента.

2023-12-26 13:48 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        ingredientsAdapter = recipeIngredients?.let { IngredientsAdapter(recipeIngredients!!) }
Тут сразу 2 комментария будет
- экземпляр адаптера все еще создается каждый раз при изменении стейта `IngredientsAdapter(recipeIngredients!!)`
- как упоминалось ранее оператор "это не null" является опасным и может быть причиной падения программы, где не всегда очевидно и легко найти причины

Нужно 1 раз создать экземпляр до подписки. Можно в этом же методе. Ну и боюсь что придется все переместить в один метод инициализации UI, чтобы не передавать кучу параметров из метода в метод. на самом деле это не критично, но можешь предложить и свой вариант

2023-12-26 18:28 UTC, morganharry commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        ingredientsAdapter = recipeIngredients?.let { IngredientsAdapter(recipeIngredients!!) }
> * экземпляр адаптера все еще создается каждый раз при изменении стейта `IngredientsAdapter(recipeIngredients!!)`
> ...
> Нужно 1 раз создать экземпляр до подписки. Можно в этом же методе. Ну и боюсь что придется все переместить в один метод инициализации UI, чтобы не передавать кучу параметров из метода в метод. на самом деле это не критично, но можешь предложить и свой вариант


нужны пояснения. Как создать до подписки? Минуя стейт?

2023-12-27 11:16 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        ingredientsAdapter = recipeIngredients?.let { IngredientsAdapter(recipeIngredients!!) }
отписал в ЛС

2023-12-30 22:26 UTC, ievetrov requested changes

2023-12-30 22:26 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        ingredientsAdapter.dataSet = viewModel.recipeLiveData.value?.recipe?.ingredients ?: listOf()
Обращаясь напрямую к стейту вне подписки все преимущества LiveData сводятся на нет.

А преимущества такие – загрузка данных может осуществляться не сразу. Сейчас проблем нет, тк все грузится прям из кода проекта и быстро. Но при загрузке из базы или сети возникнут проблемы. Это не такой быстрый процесс.

Соответственно рецепт может быть пустой к этому моменту. А `initUI` вызывается только один раз при создании фрагмента и повторного шанса проинициализировать адаптеры уже не будет.

Вывод – есть 2 варианта: отказаться от стейтов вообще и обращаться напрямую к файлу, либо сделать подписку и брать значения только из стейта.

2024-01-05 13:42 UTC, ievetrov approved these changes
Да, так лучше)

Что сейчас происходит. 
1. Вызываем loadRecipe, который присваивает стейту определенное состояние. Но надо понимать, что подписка на стейт еще НЕ произошла.
2. Как только производится подписка, LiveData отдает хранимое в ней значение. Поэтому рецепт рисуется.

Это происходит потому, что LiveData хранит состояние последнего элемента и при подписке он выплевывается. Затем наблюдатель остается в состоянии ожидания следующих изменений стейта.

2024-01-06 02:48 UTC, merged