RA-05_basic_button_navigation
morganharry/RecipeApp pull request #4
Opened 2023-10-31 07:00 UTC by morganharry

RA-05_added ClickListener and fragment for Favorites

2023-11-01 20:22 UTC, ievetrov requested changes

2023-11-01 20:22 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/CategoriesListFragment.kt
> +    private val binding
обрати внимание - теперь эта переменная нигде не используется. 
onCreateView нам нужно обращаться обязательно к ненулябельной переменной - в этом смысл безопасной обертки

2023-11-01 20:22 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/CategoriesListFragment.kt
>          return inflater.inflate(R.layout.fragment_list_categories, container, false)
для сохранения консистентности предпочтительнее возвращать корневой элемент разметки из байндинга.

2023-11-01 20:22 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +            buttonCategories.setOnClickListener {
тут все окей, однако при запуске приложения подтягивается activity_main. а по нашей бизнес-логике необходимо сразу же показывать фрагмент с категориями. давай это добавим в метод, кт вызывается при создании активити

2023-11-03 05:28 UTC, morganharry commented on app/src/main/java/com/example/recipeapp/CategoriesListFragment.kt
>          return inflater.inflate(R.layout.fragment_list_categories, container, false)
Поправил.

2023-11-03 05:31 UTC, morganharry commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +            buttonCategories.setOnClickListener {
Исправил, но возник вопрос  - как избавиться от повторения кода? Сейчас три блока похожих друг на друга supportFragmentManager.commit.

2023-11-05 16:42 UTC, ievetrov requested changes

2023-11-05 16:42 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/CategoriesListFragment.kt
> +    private val binding
переменная по прежнему не используется

<img width="717" alt="Снимок экрана 2023-11-05 в 19 23 51" src="https://github.com/morganharry/RecipeApp/assets/34489023/92fa3534-b809-4a81-9f11-27995665518e">

2023-11-05 16:42 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/CategoriesListFragment.kt
>          return inflater.inflate(R.layout.fragment_list_categories, container, false)
Здесь происходит повторный вызов `inflate()`, лучше соблюсти консистентность и продолжать использовать подключенный ViewBinding. Ну и помимо чистоты кода, не заработает обращение к binding, если не возвращать корневой элемент разметки `binding.root`

2023-11-05 16:42 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/FavoritesFragment.kt
> +        return (binding.root)
а вот тут все верно

2023-11-05 16:42 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +            buttonCategories.setOnClickListener {
Для оптимизации этого кода можно создать метод навигации, который будет принимать фрагмент с типом Фрагмент. а внутри тот же самый реплейс

Но опционально можно оставить, потому что используя Jetpack Navigation будет все гораздо компактнее

2023-11-05 17:09 UTC, ievetrov approved these changes

2023-11-05 17:10 UTC, merged