RA-38_jetpack_room
morganharry/RecipeApp pull request #44
Opened 2024-02-05 02:48 UTC by morganharry

2024-02-05 03:36 UTC, morganharry commented
![image](https://github.com/morganharry/RecipeApp/assets/101452247/3d108bc5-3e9e-48ab-b82f-309c0266d385)

2024-02-05 17:40 UTC, ievetrov requested changes
kotlin("plugin.serialization") version "1.9.21"
id("org.jetbrains.kotlin.android") version "1.9.0"
id("com.google.devtools.ksp") version "1.9.22-1.0.17"

разношерстные версии языка могут сыграть непредсказуемо. давай приведем все плагины к последней версии языка Котлин

Также приложи еще скрин с найденными файлами Shared Preferences

2024-02-06 08:31 UTC, morganharry commented
> kotlin("plugin.serialization") version "1.9.21" id("org.jetbrains.kotlin.android") version "1.9.0" id("com.google.devtools.ksp") version "1.9.22-1.0.17"
> 
> разношерстные версии языка могут сыграть непредсказуемо. давай приведем все плагины к последней версии языка Котлин
> 
> Также приложи еще скрин с найденными файлами Shared Preferences

обновил

2024-02-06 08:31 UTC, morganharry commented
Скрин
![image](https://github.com/morganharry/RecipeApp/assets/101452247/0a42bcfe-9fde-4cf4-9df4-9f25055d8d19)

2024-02-06 14:01 UTC, morganharry commented
![image](https://github.com/morganharry/RecipeApp/assets/101452247/97edaa0b-fb56-47bb-9854-aada6e4f6456)

2024-02-06 15:21 UTC, ievetrov approved these changes

2024-02-06 15:47 UTC, merged