RA-40_caching2
morganharry/RecipeApp pull request #46
Opened 2024-02-14 15:17 UTC by morganharry

2024-02-16 01:07 UTC, danelyan requested changes
> Т.к. мы загружаем список рецептом по id категории, то мы можем выстроить связь "один к многим", как рекомендует документация.
Но в то же время, для мне необходимо ввести новое свойство для класса рецепта - id родительской категории. Но тогда зачем мне моделировать привязки между объектами и создавать новый класс данных, если я могу запрашивать список рецептов из таблицы рецептов выбирая только по этому параметру?


Все верно, давай добавим id-категории и по нему будем запрашивать список. Только давай добавим `@Transient` аннотацию к полю id-категории. Чтобы сделать невидимым для сериализации Kotlinx

2024-02-16 01:07 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/data/Database.kt
> +@Database(entities = [Category::class], [Recipe::class], version = 1)
Обрати внимание сюда:
```Kotlin
@Database(entities = [Category::class], [Recipe::class], version = 1)
```
тут:
- Database - название аннотации
- entities - название параметра
- [Category::class] - значение для параметра entities, список классов, которые Room будет воспринимать как таблицы
- version = 1 - другой параметр со значением 1. Описывает версию схемы базы данных. Схема, это по сути колонки и их типы. На случай если схема меняется, нужно корректным образом мигрировать данные. Но это оффтоп
-  [Recipe::class] - в данном случае представляет второй параметр аннотации Database. А если заглянуть внутрь, мы как раз и увидим Views:
<img width="400" alt="Screenshot 2024-02-16 at 03 53 26" src="https://github.com/morganharry/RecipeApp/assets/7125622/08f22038-c40b-4173-b2cc-db9178858140">

Термин View (представление), в данном контексте не относится к UI. Здесь речь про представления данных. Это когда у тебя запрос выглядит как таблица и с ним можно работать.

https://developer.android.com/training/data-storage/room/creating-views

Просто удали `], [`

2024-02-16 01:07 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/model/Recipe.kt
> +    @ColumnInfo(name = "ingredients") val ingredients: List<Ingredient>,
После того как починишь "must be annotated with DatabaseView" (см выше), у тебя поломается тут. Room начнет просить при компиляции объяснить ему, "а как хранить список Ingredient?".

И сама же даст совет: `You can consider adding a type converter for it.`
То есть предложит создать конвертор типа, который "объяснит" Room как сохранять ingredients в ячейку таблицы и как восстанавливать.
Для этого можешь воспользоваться Kotlinx Json Serialization, а выглядеть это будет примерно так:

```Kotlin
class Converters {

    // ...

    @TypeConverter
    fun fromIngredientsList(list: List<Ingredient>?): String {
        return Json.encodeToString(list ?: emptyList())
    }

    @TypeConverter
    fun toIngredientsList(value: String): List<Ingredient> {
        return try {
            Json.decodeFromString(value)
        } catch (e: Exception) {
            emptyList()
        }
    }

    // ...
}
```

Останется указать этот классс в аннотации к AppDatabase:
```Kotlin
@TypeConverters(Converters::class)
```

2024-02-18 19:36 UTC, ievetrov approved these changes

2024-02-20 16:01 UTC, merged