RA-07_layout_list_of_categories
morganharry/RecipeApp pull request #6
Opened 2023-11-08 10:45 UTC by morganharry

2023-11-08 17:47 UTC, morganharry commented
Вопросы:
1. > Сверстать во фрагменте шапку с изображением и заголовком.
Не получается сверстать так, чтобы при любом экране картинка занимала всю ширину, и соответственно текст не выходил за ее пределы. Нужна помощь.
2. > Сверстать отдельный лейаут item_category.xml для элемента списка категории (карточку 'Категория').
Сверстал, но т.к. это типовая вёрстка для всех элементов, то View заполнять не стал, только указал id. Предполагаю , что далее мы будет эту вёрстку наполнять

2023-11-08 18:42 UTC, ievetrov requested changes

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +    android:id="@+id/fragment_favorites"
по моему тут перепутано теперь наоборот. это же фрагмент с категорийми?

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +    tools:context=".FavoritesFragment"
И контекст тоже поменялся

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +        >
вот таких пустых пространств лучше не коммитить. не забывай применять автоформатирование перед коммитом

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +        android:layout_height="0dp"
Высоту задаем точную. Список у нас будет скроллиться, а вот шапка жестко зафиксирована

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +        android:layout_weight="1"
соответственно и веса тут не потребуются

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +            app:layout_constraintTop_toTopOf="parent" />
можно добавить остальные два констрейнта. будет занимать все пространство

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +            app:layout_constraintTop_toTopOf="parent" />
Посмотри как работает атрибут scaleType. Он поможет растянуть и центрировать картинку

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +            android:layout_marginStart="10dp"
у нас уже есть вынесенные в ресурсы стандартные отступы для этого

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +            android:text="@string/button_categories"
чтобы не сбивало с толку лучше изменить название ресурса на что то вроде title_cat...

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +        tools:text="Заголовок"/>
можно мокать реальные заголовки. и ничего что они одинаковые

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +        tools:text="Текст для описания категории элементов списка"/>
и тут

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +<androidx.appcompat.widget.LinearLayoutCompat xmlns:android="http://schemas.android.com/apk/res/android"
Предлагаю использовать основной контейнер CardView. Идеально подходит для карточки и имеет тень по умолчанию. У карточки есть атрибут cardCornerRadius

2023-11-08 18:42 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +    <ImageView
соответственно тоже применяем атрибут центрирования изображения

2023-11-09 04:43 UTC, morganharry commented on app/src/main/res/layout/fragment_list_categories.xml
> +        android:layout_height="0dp"
Точную как в макете? Заголовок за пределы картинки уходит(
![Снимок5](https://github.com/morganharry/RecipeApp/assets/101452247/8c1ad7b3-3513-4f4d-848e-85e18b49867f)

2023-11-09 19:08 UTC, ievetrov approved these changes

2023-11-10 09:07 UTC, merged