RA-10_initial
morganharry/RecipeApp pull request #9
Opened 2023-11-14 14:12 UTC by morganharry

2023-11-15 10:58 UTC, ievetrov requested changes

2023-11-15 10:58 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/RecipesListFragment.kt
> +        categoryId = requireArguments().getInt(ARG_CATEGORY_ID)
давай объединим все в блок обращаясь к проперти `arguments` используя `let`
`arguments?.let { ...`

2023-11-15 10:58 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/RecipesListFragment.kt
> +        categoryId = requireArguments().getInt(ARG_CATEGORY_ID)
и внутри достаем все три объекта из бандл

2023-11-15 10:58 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/CategoriesListFragment.kt
> +const val ARG_CATEGORY_ID: String = ""
Предлагаю в корне создать файл Constants.kt и в нем объявлять эти и все новые константы

2023-11-15 20:05 UTC, ievetrov requested changes

2023-11-15 20:05 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/Constants.kt
> +const val ARG_CATEGORY_ID: String = ""
так, важный момент, я сразу не обратил внимания сорри. 
смотри, в доке значения получаем по каким-либо ключам. ключи мы поместили в константы. собственно в значениях надо прописать уникальные ключи.

2023-11-15 20:05 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/Constants.kt
> +const val ARG_CATEGORY_ID: String = ""
тут будет `argCategoryId` и далее по аналогии

2023-11-16 06:03 UTC, morganharry commented on app/src/main/java/com/example/recipeapp/Constants.kt
> +const val ARG_CATEGORY_ID: String = ""
> тут будет `argCategoryId` и далее по аналогии

просто как строку? Добавил. На что это влияет?

2023-11-16 06:04 UTC, morganharry commented on app/src/main/java/com/example/recipeapp/RecipesListFragment.kt
> +        categoryId = requireArguments().getInt(ARG_CATEGORY_ID)
> и внутри достаем все три объекта из бандл
`    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        arguments?.let {
            categoryId = it.getInt(ARG_CATEGORY_ID)
            categoryName = it.getString(ARG_CATEGORY_NAME)
            categoryImageUrl = it.getString(ARG_CATEGORY_IMAGE_URL)
        }
    }`
    
    Все верно?

2023-11-16 06:05 UTC, morganharry commented on app/src/main/java/com/example/recipeapp/RecipesListFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
Все верно?

2023-11-16 06:07 UTC, morganharry commented on app/src/main/java/com/example/recipeapp/RecipesListFragment.kt
> +        categoryId = requireArguments().getInt(ARG_CATEGORY_ID)
> и внутри достаем все три объекта из бандл

Сейчас все правильно? Я просто не уверен. Выглядит будто бы неочень)

2023-11-16 14:25 UTC, merged

2023-11-16 17:00 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/Constants.kt
> +const val ARG_CATEGORY_ID: String = ""
Верно, теперь у всех ключи - разные строки

2023-11-16 17:02 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/RecipesListFragment.kt
> +        categoryId = requireArguments().getInt(ARG_CATEGORY_ID)
Сейчас то, что нужно. но в будущем сделаем еще короче)